# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: SPC
version: "1.2.3"
slug: spc
description: Plugin to read SPC data without SPC Web Gateway
url: "https://github.com/Sandr0x00/ha-spc/tree/main"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: services
ports:
  50123/tcp: 50123